---
- name: Install Wifi Pwnage
  hosts: all
  remote_user: "{{ user }}"
  roles:
    - common
    - rtl8812au
    - gps
    - kismet
    - aircrack-ng
    - fruitywifi
    - hostapd-wpe
  become: true
