---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - raspberrypi-kernel-headers
    - build-essential
    - libssl1.0-dev
    - libgcrypt-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - ethtool
    - pkg-config
    - libpcre3-dev
    - libsqlite3-dev
    - rfkill

- name: checkout aircrack-ng
  git:
    repo: https://github.com/aircrack-ng/aircrack-ng.git
    dest: "{{ aircrack_dir }}"
    version: master
    accept_hostkey: true
    depth: 1
    force: true
  register: aircrack

- name: autoreconf
  command: autoreconf -i
  args:
    chdir: "{{ aircrack_dir }}"
  when: aircrack.changed

- name: configure
  command: ./configure
  args:
    chdir: "{{ aircrack_dir }}"
  when: aircrack.changed

- name: compile aircrack-ng
  make:
    chdir: "{{ aircrack_dir }}"
    params:
      sqlite: true
      libnl: true
      pcre: true
  when: aircrack.changed

- name: install
  make:
    chdir: "{{ aircrack_dir }}"
    target: install
    params:
      sqlite: true
      libnl: true
      pcre: true
  when: aircrack.changed
