---
- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
    - raspberrypi-kernel-headers
    - build-essential

- name: checkout driver
  git:
    repo: https://github.com/aircrack-ng/rtl8812au.git
    dest: /opt/rtl8812au
    version: v4.3.21
    accept_hostkey: true

# TODO: Update make file to SUBARCH=arm

# sudo ./dkms-install.sh

# sudo cp realtek-leds.conf /etc/modprobe.d/