---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - raspberrypi-kernel-headers
    - build-essential

- name: checkout driver
  git:
    repo: https://github.com/aircrack-ng/rtl8812au.git
    dest: "{{ rtl8812_dir }}"
    version: v4.3.21
    accept_hostkey: true

- name: install and compile driver
  command: "{{ rtl8812_dir }}/dkms-install.sh"

- name: copy LED configuration
  copy:
    remote_src: yes
    src: "{{ rtl8812_dir }}/realtek-leds.conf"
    dest: /etc/modprobe.d/realtek-leds.conf
