---
- name: Remove useless packages
  apt: name={{ item }} state=absent autoremove=yes purge=yes
  with_items:
    - minecraft-pi
    - wolfram-engine
    - sonic-pi
    - pigpio

- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - curl
    - apt-transport-https
    - bash-completion
    - net-tools
    - htop
    - bluetooth
    - bluez
    - build-essential
    - raspberrypi-kernel-headers

- name: raspi main config
  copy:
    src: config.txt
    dest: /boot/config.txt

- name: Set up languages part 1
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - de_AT.UTF-8

- name: Set up languages part 2
  copy: src=locale dest=/etc/default/locale

- name: Set hostname part 1
  copy: content={{ server_name }} dest=/etc/hostname

- name: Set hostname part 2
  replace:
    path: /etc/hosts
    regexp: '^(127.0.1.1\s+)\w+$'
    replace: '\1{{ server_name }}'

- name: SSH config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart ssh

- name: Disable motd when logging in
  replace:
    path: /etc/pam.d/sshd
    regexp: '^(\s*session\s+optional\s+pam_motd\.so.*)$'
    replace: '# \1'

- name: root user SSH config
  file: path=/root/.ssh state=directory owner=root group=root

- name: authorized_keys
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys

- name: pi user SSH config
  file: path=/home/pi/.ssh state=directory owner=pi group=pi

- name: authorized_keys
  copy: src=authorized_keys dest=/home/pi/.ssh/authorized_keys

- name: Get current kernel version
  command: "uname -r"
  register: kernel_version

- name: Current kernel version
  debug:
    msg: "{{ kernel_version.stdout }}"

- name: Link kernel sources (fix arch/armv7l/Makefile error)
  file:
    src: /usr/src/linux-headers-{{ kernel_version.stdout }}/arch/arm
    dest: /usr/src/linux-headers-{{ kernel_version.stdout }}/arch/armv7l
    state: link

# pair bluetooth keyboard
# https://medium.com/@elkentaro/snooppi-a-raspberry-pi-based-wifi-packet-capture-workhorse-part-1-n-for-snooppi-1fa14ed67e01
