---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - gpsd
    - gpsd-clients

- name: run gps daemon
  command: gpsd {{ gps_device }}

- name: Copy default configuration
  template: src=gpsd.default dest=/etc/default/gpsd

# sudo dpkg-reconfigure gpsd

# kismet config
# gps=gpsd:host=localhost,port=2947,reconnect=true
